### PR TITLE
Bugfix for issue: ModuleNotFoundError: No module named 'server_parser…

### PR DESCRIPTION
**Pull request by shaikhwaris**
…_status_metrics'

added module path to fix the bug

### CODE REVIEW

**Comment by dhuang** [comment]
@ilyasemenov84 or @zstoth, any chance we can get this one merged in too?

**Comment by zstoth** [comment]
> @ilyasemenov84 or @zstoth, any chance we can get this one merged in too?

I think this change shouldn't be required if the application is installed correctly. How do you install it?

**Comment by dhuang** [comment]
Sorry for the delay @zstoth, here are my steps to reproduce. Let me know if I'm installing it incorrectly.

```
$ virtualenv env
created virtual environment CPython3.7.9.final.0-64 in 834ms
  creator CPython3Posix(dest=/<snip>/env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/dhuang/Library/Application Support/virtualenv)
    added seed packages: pip==21.0.1, setuptools==54.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ source env/bin/activate
$ python --version
Python 3.7.9
$ git clone https://github.com/hellofresh/tableau-status-exporter.git
Cloning into 'tableau-status-exporter'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 129 (delta 32), reused 53 (delta 16), pack-reused 48
Receiving objects: 100% (129/129), 33.54 KiB | 730.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
$ pip install tableau-status-exporter/
Processing ./tableau-status-exporter
...
Successfully built tableau-exporter
Installing collected packages: six, idna, attrs, zope.interface, urllib3, incremental, hyperlink, constantly, chardet, certifi, Automat, twisted, requests, pyyaml, prometheus-client, tableau-exporter
Successfully installed Automat-20.2.0 attrs-20.3.0 certifi-2020.12.5 chardet-4.0.0 constantly-15.1.0 hyperlink-21.0.0 idna-2.10 incremental-21.3.0 prometheus-client-0.10.0 pyyaml-5.4.1 requests-2.25.1 six-1.15.0 tableau-exporter-0.2.0 twisted-21.2.0 urllib3-1.26.4 zope.interface-5.3.0
$ python tableau-status-exporter/executable/main.py 
Traceback (most recent call last):
  File "tableau-status-exporter/executable/main.py", line 4, in <module>
    from tableau_exporter.tableau_status_exporter import start_webserver
  File "/<snip>/env/lib/python3.7/site-packages/tableau_exporter/tableau_status_exporter.py", line 6, in <module>
    from server_parser_status_metrics import TableauServerStatusParser
ModuleNotFoundError: No module named 'server_parser_status_metrics'
```

**Comment by anlutro** [comment]
This error will only happen in Python 3, where relative imports have to be explicit (i.e. `from .server_parser_status_metrics import ...`). You could make changes to the module/application to make it work in both Python 2 and 3, but 2 is EOL for almost a year already - so I really hope using Python 2 isn't what you're referring to when you say "install it correctly".

**Comment by zstoth** [comment]
> This error will only happen in Python 3, where relative imports have to be explicit (i.e. `from .server_parser_status_metrics import ...`). You could make changes to the module/application to make it work in both Python 2 and 3, but 2 is EOL for almost a year already - so I really hope using Python 2 isn't what you're referring to when you say "install it correctly".

That makes sense. I don't know if Hellofresh migrated to python3 already with this, but I guess it can go to master anyways. @ilyasemenov84 can this go in?

**Review by ilyasemenov84 — APPROVED** [review]
Migration to Python3 is not done yet, but we are among for it.

**Comment by anlutro** [comment]
This change should still be compatible with python2. If you want to be sure, add `from __future__ import absolute_import` to the top of the file, to tell python2 to use python3 import behavior.

**Pull request closed without merging**
